### ISSUE TITLE
Consistent casing for provider-specified values

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#104]
### Description
There should be an attribute that requires column values to use consistent casing to ensure values are grouped together given most systems do not support case-insensitive grouping. For example, "brazil" and "Brazil" would be grouped in separate rows.

### Proposed approach
Allow providers to define what casing is most appropriate for their column values, but require that the casing be consistent.

### Github issue or Reference
Applies to any column with provider-specified values.

**Comment by udam-f2** [comment]
@flanakin If still relevant, if not can we close? I know we addressed some of this in the naming convention.

**Comment by flanakin** [comment]
I haven't checked all columns, but we don't call out case-sensitivity explicitly from what I've noticed. We do say "MUST be consistent" in at least one column, but not sure if that's enough. I'm curious what others think.

**Comment by flanakin** [comment]
This one feels like a "just do it" issue that's minimally impactful. We should probably just submit a PR or close it as won't fix. Thoughts?

**Comment by ijurica** [comment]
Current FOCUS columns spec overview from consistent casing for provider specified values can be found [here](https://docs.google.com/spreadsheets/d/1xCCcKjo2lBO6IFbujuQMcy5A7Yv2bCpHMJVTkOt_rLo/edit#gid=0).

And here is the summary of the TF-1 discussion on the topic that took place on Tuesday, February 27th:

- TF-1 prefers addressing this issue globally by introducing an additional attribute (requirement) rather than addressing it through normative paragraphs specific to individual columns.
- The attribute would enforce (MUST) the use of consistent value-format and/or sets of values for all Dimensions where the values are specified by Providers.
- Additionally, we propose the removal of the current references to value-format consistency requirements in certain columns, as it may unintentionally suggest a higher priority for those particular columns.
