### ISSUE TITLE
[Proposal] Rename all column ids to snake_case_naming_convention 

### ISSUE THREAD

**Issue by iakov-aws** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#139]
### Type
>Dimension, Metric

### Proposed Change
> Current naming convention in column in CamelCase, but most of SQL tools are case insensitive and convert CamelCase to nocase, that is hard to read. Using snake_case_naming_convention would make it much simpler to use in SQL.

| Camel Case | Snake Case |
| ------------- | ------------- |
| AvailabilityZone | availability_zone |
| BillingAccountId | billing_account_id |
| BillingAccountName | billing_account_name |
| BillingCurrency | billing_currency |
| BillingPeriodEnd | billing_period_end |
| BillingPeriodStart | billing_period_start |
| ChargePeriodEnd | charge_period_end |
| ChargePeriodStart | charge_period_start |
| ChargeType | charge_type |
| InvoiceIssuerName | invoice_issuer_name |
| ProviderName | provider_name |
| PublisherName | publisher_name |
| Region | region |
| ResourceId | resource_id |
| ResourceName | resource_name |
| ServiceCategory | service_category |
| ServiceName | service_name |
| SubAccountId | sub_account_id |
| SubAccountName | sub_account_name |
| AmortizedCost | amortized_cost |

**Comment by flanakin** [comment]
FYI - We chose camel case because it's more readable and approachable for non-technical people who aren't used to lowercase names with underscores.

**Comment by shawnalpay** [comment]
Discussed in Oct 15 TF1 call.  Did not have consensus on closing.  Will plan to discuss in Oct 21 Maintainer call.

**Comment by jpradocueva** [comment]
### TF-2 call on Oct 15:
Topic: [#139](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/139) Rename all column IDs to snake case
Discussion Summary: The group briefly discussed a proposal to switch all column IDs to snake case, with the consensus being that this was unnecessary work and not aligned with the goals of the spec. There was some disagreement on whether a one-liner recommendation should be added for cases where snake case might be necessary.
Resolution: The issue was left open for further discussion in the next meeting, as the group was not fully aligned on how to handle the proposal.

**Comment by shawnalpay** [comment]
We continued discussion of this issue in the Oct 16 TF2 call.  The participants determined that the spec has been defined in pascal case for some time now, and that is unlikely to change in the foreseeable future.  We shall therefore close this issue for the time being; however, recognizing that there may be future desire for such a change, we shall either reopen this issue or create a new issue, should we hear further desire for change to snake case from our stakeholders or other individuals.

**Comment by jpradocueva** [comment]
### Summary TF-2 call on Oct 16:
[#139](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/139) Rename Column IDs to Snake Case Naming Convention 
Primary Issue: A proposal to rename all column IDs from PascalCase to snake_case for improved readability.
Core Problem: PascalCase is preferred in the current spec, but snake_case may be more readable for data engineers.
Divergent Views: Some members preferred PascalCase for consistency, while others, particularly data engineers, advocated for snake_case due to system limitations (e.g., Parquet format).
Final Agreement: The group did not reach consensus and decided to close the issue but leave it dormant for future reconsideration if more feedback emerges.
Action Items: 
[TF2-[#139](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/139)] Shawn, @shawnalpay is assigned to close the issue with a note, while the team will monitor for additional feedback on the case convention.
