### ISSUE TITLE
ChargeType: Difference between what fits in Usage vs Adjustment for discounts

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#147]
There was discussion about being more clear and crisp about where things like discounts fit in for AWS in terms of ChargeType. Currently, there's conversation about should it fit in Adjustments OR Usage.

**Comment by flanakin** [comment]
What are the details here? Is this something we should be covering in VS2?

**Comment by udam-f2** [comment]
The question was around how line items for commitment purchases and recurring lines should show up (in particularly for different discount flavors like partial up-front, no up-front, and all up-front.

Should Reserved instance up-front purchase records show as ChargeType Purchase? What about recurring items that show up hourly or at other frequencies? How about items like negations? or should all these be under 'usage' given that its negating usage line items when you actually use virtual machines.

@flanakin ^

**Comment by flanakin** [comment]
> The question was around how line items for commitment purchases and recurring lines should show up (in particularly for different discount flavors like partial up-front, no up-front, and all up-front.

Isn't this already clearly defined as ChargeCategory = "Purchase"? I'm not following the ambiguity.

> Should Reserved instance up-front purchase records show as ChargeType Purchase? 

Yes 

> What about recurring items that show up hourly or at other frequencies? 

Since you're referring to hourly, I'm assuming you're talking about the usage charges. If you're talking about the recurring monthly payments, those are expected to be "Purchase" rows. If that isn't clear, we should use this to drive that clarity in the exisitng content.

> How about items like negations? 

We should clearly call these out as "after-the-fact adjustments" today. If not, let's make it clearer. The intent is there.

**Comment by shawnalpay** [comment]
@udam-f2 Now that 1.1 is done, what's your thought on this issue -- still outstanding?

**Comment by udam-f2** [comment]
This should be closed. Much of the work for this happened between 1.0-preview and 1.0 - so now we have ChargeClass for specifying detailed corrections, Charge Category 'Adjustments' for bulk corrections, the ability to differentiate the purchases of discounts, and the ability to highlight covered usage.
