### ISSUE TITLE
Should the specification reference a higher-level data dictionary for cloud / infra terminology?

### ISSUE THREAD

**Issue by udam-f2** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#25]
### Description
Concepts like 'resource' and other things referenced in FOCUS have a particular meeting not just in a billing context but broadly in cloud / infra context. Should FOCUS reference something external for these definitions? OR should this context be included in the specification?

### Github issue or Reference
General spec-wide decision

**Comment by flanakin** [comment]
We should see what exists in a time-boxed way. If we don't see anything, then let's define what we need to. We can always adjust as we learn more.

**Comment by mike-finopsorg** [comment]
We can be pretty flexible outside of the normative content. In the informative content (examples, supporting information) we can use specific examples and draw parallels. In the normative content we need to be careful and clear where something could apply unintentionally to a billing item due to the naming standards of a cloud bill generator.

**Comment by udam-f2** [comment]
Glossary introduced in v1.0
