### ISSUE TITLE
[Proposal] Invoice ID column

### ISSUE THREAD

**Issue by flanakin** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#302]
### Type
> Dimension
> Normalized: No

### Description
> Need a way to map a charge back to a specific invoice.

### Definition of done
- [x] Rationalize vendor-neutral, cross-cloud naming
- [x] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

<br>

### Give it a 👍 below ↴

If you can discuss and help finalize the change, add yourself as an assignee ↗

Comments are welcome and encouraged!

**Comment by udam-f2** [comment]
A couple of questions here:
- invoice information may not come till after the month - which could be a problem unless we're saying its unavoidable that you will have to reprocess all data at the end of a month when an invoice is generated (this is the case today for some due to data changes but we're hoping to go in a direction where there's a completeness to data that consumers can depend on at a future time) @rileyjenk FYI
- Can it be a separate mapping (e.g. billing account id + billing period -> 1 or more invoice ids)

**Comment by flanakin** [comment]
Understood re: reprocessing data. Do other providers include an InvoiceId or is it only Microsoft? Do practitioners need an InvoiceId?

The "or more" is the issue where you need an invoice ID in the data. Without that, it's not completely clear which charges go on which invoice.

**Comment by jpradocueva** [comment]
Classified as `Billing` by the Maintainers on the May 24 call

**Comment by bmcculloch95** [comment]
Hi everyone, I just wanted to express a continued interest in this topic! Having the invoice ID would be a big help for larger organizations/resellers with multiple payer accounts to assist in chargebacks. Not having an invoice ID, particularly when interfacing with Finance teams, can be a full blocker in gaining support of the specification to address their challenges.

**Comment by shawnalpay** [comment]
Thanks @bmcculloch95 for that perspective!  Labelling this one for 1.2 consideration.

**Comment by shawnalpay** [comment]
Closing this in favor of #615.
