### ISSUE TITLE
[Proposal]: Multiple values for Service Category 

### ISSUE THREAD

**Issue by rupagcp** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#326]
### Proposed Change

Multiple allowed values for ServiceCategory

### What FinOps use cases cannot be performed without the proposed change?

If customers want to understand which usage is related to the Service Category Databases AND Compute, they should be able to. In the current spec, you have to select one. Here is the supporting reasoning: 
https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/supporting_content/columns/servicecategory.md

But I am unclear why this is the case? Wouldn't it be helpful to have the Category descriptors relevant to the Service; whether it's one or many?

### Which FinOps personas perform this use case?

FinOps Practitioner

### For which providers do you perform this use case for?

GCP

### Criticality Scale

2: Important for adoption in the next 3-6 months

### Context / Supporting information

Here is the support content link - https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/supporting_content/columns/servicecategory.md

**Comment by udam-f2** [comment]
@rupagcp can you comment if this is accomplished by the SKU Categorization that's been discussed previously?

> If customers want to understand which usage is related to the Service Category Databases AND Compute, they should be able to

Service Category is defined as the `highest-level classification of a service based on the core function of the service`. However, as we all know, usage for most services are charged based on the particular SKU that you're using (captured by SKU ID and SKU Price ID). There are many asks for further sku level details (a few are common, many are specific to the type of SKU or service). SKU Category for example is one of those that have been discussed and are currently scheduled as a fast-follow to v1.0. 

If your proposal is about Cloud SQL being categorized as 'Database' but having charges for compute and network egress etc., that would get resolved when SKU Category is available because each row will then have the ability to additionally classify what you were being charged for within your 'Database' service.

Instead, if your proposal is about Cloud SQL being able to be categorized as multiple service categories (e.g. 'Database' and also 'Web' hypothetically), then that would open the discussion starting from the Service Category column definition and if a service can have a single 'highest-level' categorization. 

Keep in mind that we will still have a chance to define a further drill-down/subcategorization (e.g. ServiceSubCategory) in the future. For example, ServiceCategory 'Database' may support ServiceSubCategory values such as 'Relational Database', 'Data Warehouse' etc.). I don't think that's what you're referring to.

**Comment by udam-f2** [comment]
Moving to Triage to discuss in maintainers meeting. @rupagcp please comment beforehand so we can review this and scope in the maintainer meeting next Monday (3/4/2024)

**Comment by rupagcp** [comment]
For any future cases, we can use the working groups as a starting point for discussion to triage
