### ISSUE TITLE
Add the capability to calculate savings resulting from negotiation activities

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#336]
### Type
> Potentially multiple columns

### Description
> Practitioners require the capability to calculate savings resulting from negotiation activities. To facilitate this, we suggest exploring the following options:
> - NegotiatedUnitPrice and NegotiatedCost columns
> - NegotiatedDiscount column
> - Considering other potential alternatives

### Related Issues
> - #310 
> - #237 (related PR: #238)

### Definition of done

- [ ] Rationalize vendor-neutral, cross-cloud naming
- [ ] Complete spec template and include naming (code name, display name), constraints, guidelines, compatibility with major providers etc.

**Comment by kk09v** [comment]
One thing I've been thinking about is that if we are capturing multiple discount types applying to the same resource/record, do we need to specify the order of operations for which the discounts are applied? A simple example: if I have 2 discounts for 10% each applied to one resource, I get a 19% discount on that resource 1 - ((1-0.1) * (1-0.1));  So which discount gets the 10% (applied first) and which gets the 9% (applied second) or do they both get 9.5% (somehow)?

With contractual pricing, I think the answer is clear that contractual discounts take effect first before other discounts, but even this is messy, as the below scenario tries to illustrate.

An example of this using fake, round numbers for illustration:
- A company negotiates a 20% discount (vs list) on PAYGo usage of a VM
- At list price, a commitment grants you a 30% discount vs PAYGo of that same VM
- The company only receives a 10% discount of of the reservation price of that VM
Math time
- Lp = List Price of PAYGo | Cp = Contractual Price of PAYGo | Lc = List price of a Commitment | Cc = Contractual price of a commitment
- Cc = 0.9 Lc | Lc = 0.7 Lp ∴ Cc = 0.63 Lp Commitments under contractual pricing are a 37% discount from list
- Cp = 0.8 Lp | Cc = 0.63 Lp ∴ Cc = 0.7875 Cp Commitments under contractual pricing are a 21.25% discount from PAYGo contractual pricing, which is what the company will be looking at when evaluating whether to purchase a commitment

The attribution of the 37% savings vs list could either be (7% contractual, 30% commitment) or (20% contractual, 17% commitment), depending on which you apply first. I'd say that the first scenario (7%, 30%) is more likely because it reflects the discount vs list price of the commitment SKU you're being billed for (same line item), but if a practitioner is evaluating the impact of their commitment program and their contractual negotiations, I know I personally would want the latter.

If not specified, would all providers calculate this the same way?

**Comment by marc-perreaut** [comment]
How is this issue different from https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/237 ?

**Comment by ijurica** [comment]
> How is this issue different from #237 ?

By mistake, I listed the related PR (#238) instead of the issue (#237) in the list of related issues :(

**Comment by ijurica** [comment]
On Tuesday, February 27th, TF-1 reopened the discussion on the topic. Further offline and in-meeting deliberations are required.

To facilitate further discussion, prior to the next TF-1 meeting (preferably by Monday, March 4th, 2024):

- Compile a Google Spreadsheet containing FOCUS columns relevant for the discussion, list UCs, and include some sample data.
- Assess the current status of the [NegotiatedCost](#238) and [NegotiatedUnitPrice](#236) pull requests, in case we opt to maintain them rather than introducing NegotiatedDiscount or exploring alternative options.

**Comment by flanakin** [comment]
Negotiated discounts is one perspective. The other perspective is savings from commitment discounts. Let's please keep in mind that not all organizations have negotiated discounts. The more inclusive definition of this is that we are defining the unit price an organization pays when they use services with on-demand pricing. This applies to every organization, whether they have negotiated discounts or not. Given we already have that defined, We should use the more inclusive and consistent term here and use `OnDemandUnitPrice` and `OnDemandCost`.

**Comment by ijurica** [comment]
**Discussion topics:**

1. Preference regarding the inclusion of Unit Price and Cost columns versus Discount columns or other alternatives.
2. Column names (`Negotiated `vs `OnDemand`), should we decide to include Unit Price and Cost columns

**Specification Suggestions**

In case we opt for Unit Price and Cost columns, here are specification suggestions (based on current List Unit Price and List Cost specifications):

># Negotiated/OnDemand Unit Price
>
>The Negotiated/OnDemand Unit Price represents the agreed-upon unit price for a single [Pricing Unit](#pricingunit) of the associated SKU, inclusive of negotiated discounts, if present, and exclusive of any other discounts. This price is denominated in the [Billing Currency](#billingcurrency). The Negotiated/OnDemand Unit Price is commonly used for calculating savings based on negotiation activities. If negotiated discounts are not applicable, the Negotiated Unit Price defaults to the [List Unit Price](#listunitprice). 
>
>The Negotiated/OnDemandUnitPrice column MUST be present in the billing data. This column MUST be a Decimal within the range of non-negative decimal values, MUST conform to [Numeric Format](#numericformat), and be denominated in the BillingCurrency. Negotiated/OnDemandUnitPrice MUST NOT be null if [SkuPriceId](#skupriceid) is not null and MUST be null if SkuPriceId is null. When Negotiated/OnDemandUnitPrice is not null, multiplying Negotiated/OnDemandUnitPrice by [PricingQuantity](#pricingquantity) MUST equal [Negotiated/OnDemandCost](#listcost). 

># Negotiated/OnDemand Cost
>
>Negotiated/OnDemand Cost represents the cost calculated by multiplying [Negotiated/OnDemand Unit Price](#negotiated/ondemandunitprice) and the corresponding [Pricing Quantity](#pricingquantity). Negotiated/OnDemand Cost is denominated in the [Billing Currency](#billingcurrency) and is commonly used for calculating savings based on negotiation activities, by comparing it with [List Cost](#listcost). If negotiated discounts are not applicable, the Negotiated Cost defaults to the List Cost.
>
>The Negotiated/OnDemandCost column MUST be present in the billing data and MUST NOT be null. This column MUST be of type Decimal, MUST conform to [Numeric Format](#numericformat), and be denominated in the BillingCurrency. When a Negotiated/OnDemandUnitPrice is not null, multiplying the Negotiated/OnDemandUnitPrice by PricingQuantity MUST produce the Negotiated/OnDemandCost.
>
>In cases where the Negotiated/OnDemandUnitPrice is null, the following applies:
>
>* The Negotiated/OnDemandCost MUST be calculated based on the Negotiated/OnDemandCost of the related charges if the charge is calculated based on other charges (e.g. [ChargeCategory](#chargecategory) is "Tax").
>* The Negotiated/OnDemandCost MUST match the [BilledCost](#billedcost) if the charge is unrelated to other charges (e.g. [ChargeSubcategory](#chargesubcategory) is "Credit").

**Comment by ijurica** [comment]
For further discussions, collaboration, and feedback, please proceed to the corresponding PR - https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/364
