### ISSUE TITLE
[DISCUSSION]: Issue Template Discussion

### ISSUE THREAD

**Issue by jpradocueva** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#604]
### Document:
* Spreadsheet: [24.10.14 FOCUS Issues Template Analysis](https://docs.google.com/spreadsheets/d/1XWB2b_FyAn2v-daU9QW8RxX18IR6uhMfKrBNbwt7kdk/edit?gid=0#gid=0)

### Proposed Approach

Review current list of Issue templates.

### Context

This topic was discussed during the Maintainers' call on Oct 14.
Any topic under discussion should have an issue # to track easily.

**Comment by jpradocueva** [comment]
### Action Items assigned during the Maintainers' call on Oct 14:
- [ ] [Maintainers-[#604](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/604)] Assigned to Irena, @irurica: will finalize a spreadsheet detailing a comparison of existing templates and then propose changes to streamline the templates based on today’s agreements.

**Comment by flanakin** [comment]
My requests:
1. Remove the Spec Change issue template. It's replaced by the new one.
2. Remove the Discussion Topic issue template. Any topics to discuss are effectively "feedback". 
3. Should the combined feedback/feature request form have a "FEEDBACK" prefix?
4. Change the FinOps personas to a checkbox list so people know what the options are without having to look them up 😜
5. Do we need to differentiate providers in the feedback form? If so, can we make it a checkbox list with an "Other" option? Would it make more sense to use larger buckets, like Public cloud, Private cloud, On-premises, SaaS, etc?
6. Criticality scale only makes sense for practitioners. Should that be optional or do you want non-practitioners to give their best guess? Note this won't be accurate as people upvote requests.
7. Key metrics and KPIs is not 100% clear as to what it is asking. Is this about KPIs that can be calculated with the new data or KPIs that will determine success of us making a change. The former feels duplicative of the scenarios question.
8. The data submission box doesn't feel adequate for what we actually need. I would remove that and make it a step in the process rather than part of the form.

Sorry for the late feedback on the template. I didn't want to delay getting the basic form in, since this is something we will mature over time.

**Comment by jpradocueva** [comment]
### Summary Members' call on Oct 17:
[#604](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/604) [DISCUSSION]: Issue Template Discussion
Primary Issue: A discussion on improving the existing issue templates, with the primary focus on balancing simplicity for community contributions and rigor for complex work items.
Core Problem: The existing issue templates were seen as insufficient for defining complex work items, and there was a need for more structured guidance to ensure that issues captured all necessary details.
Divergent Views: Some members felt that the more complex templates could deter community contributions due to higher entry barriers, while others argued that more detailed templates are necessary to ensure that all relevant information is captured, especially for maintainers.
Final Agreement: The group agreed to maintain the simpler issue templates for general contributions while introducing more rigorous templates for work items that require detailed problem statements, objectives, and supporting documentation.
Action Items:
- [ ] [Members-[#604]](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/604) Irena @ijurica : Present recommendations on revising or collapsing other existing issue templates to align with the new work item format.

**Comment by jpradocueva** [comment]
### Action Items from Maintainers' call on Oct 21:
- [ ] [[#604](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/issues/604)] Irena @ijurica  to rewrite the template as proposed and share updates with the team.
